# -*- coding: utf-8 -*-
"""Lab_bezier_curve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSDV7VZxLWrC5G9F0oxhMxJaTUpUF18m
"""

import pygame
import time



pygame.init()
pygame.display.set_caption("cubic bezier cuve")
screenSize = (900, 600)
screen = pygame.display.set_mode(screenSize)

x,y = 70.0, 70.0
width, height = 30, 30
speed = 0.001


def pathPosition(path_position):


    t=0

    running = True

    while running:
        screen.fill((0,0,0))
        pygame.time.delay(100)
        p0 = path_position[0]
        p1 = path_position[1]
        p2 = path_position[2]
        p3 = path_position[3]

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        while t < 1:
            t += speed
            p0_x = pow((1-t),3)*p0[0]
            p0_y = pow((1-t),3)*p0[1]

            p1_x = 3*pow((1-t),2)*t*p1[0]
            p1_y = 3*pow((1-t),2)*t*p1[1]

            p2_x = 3*(1-t) * pow(t,2)*p2[0]
            p2_y = 3*(1-t) * pow(t,2)*p2[1]

            p3_x = pow(t,3) * p3[0]
            p3_y = pow(t,3) * p3[1]

            formular = ((p0_x+p1_x+p2_x+p3_x),(p0_y+p3_y+p2_y+p1_y))
            x, y = formular

            pygame.draw.line(screen, (0,255,0),p0, p1, 1)
            pygame.draw.line(screen, (0,0,255),p2, p3, 1)
            pygame.draw.circle(screen, (255,255,255),(round(x), round(y)),1)
            pygame.display.update()

    pygame.quit()

        

path_position = [(100.0,480.0),(300.0,100.0),(300.0,180.0),(850.0,410.0)]
pathPosition(path_position)